DROP TABLE IF EXISTS creature CASCADE;
DROP TABLE IF EXISTS action CASCADE;
DROP TABLE IF EXISTS  action_consequence CASCADE;
DROP TABLE IF EXISTS  human CASCADE;
DROP TABLE IF EXISTS  mind_status CASCADE;
DROP TABLE IF EXISTS sensation CASCADE;
DROP TYPE IF EXISTS creature_enum CASCADE;